### PR TITLE
Fixed Products Page

### PR DESCRIPTION
**Pull request by SimranjitKaurMaan**
Fixed Products Page:

image

### CODE REVIEW

**Review by kalyandindu — APPROVED** [review]
Code looks clean and good usage of utility classes.

**Review by shubhamkumar648 — APPROVED** [review]
as i seen you already modified  changes  and code look good , you can merge

**Comment by SimranjitKaurMaan** [comment]
> as i seen you already modified changes and code look good , you can merge

Thanks for reviewing.

**Comment by SimranjitKaurMaan** [comment]
> Code looks clean and good usage of utility classes.

Thanks for reviewing.

**Pull request merged**
